-- DDL
COMMIT;
-- Data Definition Language 데이터 정의어
-- 오라클의 객체를 생성, 수정, 삭제하는 명령어, 명령어의 종류로는
-- CREATE, ALTER, DROP, TRUNCATE, ...

COMMENT ON COLUMN EMPLOYEE.NAME IS '사원명';
COMMENT ON COLUMN EMPLOYEE.T_CODE IS '직급코드';
COMMENT ON COLUMN EMPLOYEE.D_CODE IS '부서코드';
COMMENT ON COLUMN EMPLOYEE.AGE IS '나이';

DESC EMPLOYEE;

DESC USER_UNIQUE;

DESC SHOP_MEMBER;

DESC SHOP_BUY;

-- 계정을 만들어주세요
-- 접속정보(ID/PW) : KH / KH
-- 접속권한, 생성권한 부여
-- system red
CREATE USER KH IDENTIFIED BY KH;
GRANT CONNECT, RESOURCE TO KH;

-- kh violet
-- ALTER (오라클 객체)
-- ALTER를 이용한 제약조건 추가, 수정, 이름변경
-- ALTER를 이용한 컬럼 추가, 컬럼데이터타입 수정, 컬럼명 수정, 컬럼 삭제, 테이블명 수정
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEE';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEPARTMENT';
-- ** CONSTRAINT TYPE
-- P : PRIMARY KEY
-- R(F) : FOREIGN KEY
-- C : CHECK OR NOT NULL
-- U : UNIQUE

CREATE TABLE USER_GRADE(
    GRADE_CODE NUMBER,
    GRADE_NAME VARCHAR2(30)
);

DROP TABLE USER_FOREIGN_KEY;
DROP TABLE USER_GRADE;
INSERT INTO USER_GRADE VALUES(10, '일반회원');
INSERT INTO USER_GRADE VALUES(20, '우수회원');
INSERT INTO USER_GRADE VALUES(30, '특별회원');
INSERT INTO USER_GRADE VALUES(40, 'VIP회원');
DELETE FROM USER_GRADE WHERE GRADE_CODE = 40;
SELECT * FROM USER_GRADE;

CREATE TABLE USER_FOREIGN_KEY(
    USER_NO NUMBER,
    USER_ID VARCHAR2(20),
    USER_PWD VARCHAR2(30),
    USER_NAME VARCHAR2(30),
    USER_GENDER VARCHAR2(10),
    USER_PHONE VARCHAR2(30),
    USER_EMAIL VARCHAR2(50),
    USER_DATE DATE DEFAULT SYSDATE,
    GRADE_CODE NUMBER
);

INSERT INTO USER_FOREIGN_KEY
VALUES(1, 'khuser01', 'pass01', '일용자', 'M', null, null, DEFAULT, 10);
INSERT INTO USER_FOREIGN_KEY
VALUES(2, 'khuser02', 'pass02', '이용자', 'M', null, null, DEFAULT, 20);
INSERT INTO USER_FOREIGN_KEY
VALUES(3, 'khuser03', 'pass03', '삼용자', 'M', null, null, DEFAULT, 30);
INSERT INTO USER_FOREIGN_KEY
VALUES(4, 'khuser04', 'pass04', '사용자', 'M', null, null, DEFAULT, 40);
SELECT * FROM USER_FOREIGN_KEY;

DESC USER_GRADE;
-- 1. 테이블의 컬럼 추가
-- 2. 테이블의 컬럼 삭제
-- 3. 테이블의 컬럼데이터타입 수정
-- 4. 테이블의 컬럼명 수정
-- 5. 테이블명 수정
-- 1. 테이블의 컬럼 추가
ALTER TABLE USER_GRADE
ADD GRADE_DATE DATE;
-- 2. 테이블의 컬럼 삭제
ALTER TABLE USER_GRADE
DROP COLUMN GRADE_DATE;
DESC USER_GRADE;
SELECT * FROM USER_GRADE;
-- 3. 테이블의 컬럼데이터타입 수정
ALTER TABLE USER_GRADE
MODIFY GRADE_NAME CHAR(12);

ALTER TABLE USER_GRADE
ADD GRADE_DATE DATE;
-- 4. 테이블의 컬럼명 수정
ALTER TABLE USER_GRADE
RENAME COLUMN GRADE_DATE TO REG_DATE;
-- 5. 테이블명 수정
ALTER TABLE USER_GRADE
RENAME TO GRADE_TBL;

SELECT * FROM USER_GRADE;

RENAME GRADE_TBL TO USER_GRADE;

-- 제약조건과 ALTER
-- 1. 제약조건 추가
-- 2. 제약조건 삭제
-- 3. 제약조건 수정
DROP TABLE USER_FOREIGN_KEY;
DROP TABLE USER_GRADE;
CREATE TABLE USER_GRADE(
    GRADE_CODE NUMBER,
    GRADE_NAME VARCHAR2(30)
);
-- 1. 제약조건 추가
ALTER TABLE USER_GRADE
ADD CONSTRAINT PK_GRADE_CODE PRIMARY KEY(GRADE_CODE);

ALTER TABLE USER_FOREIGN_KEY
ADD CONSTRAINT FK_GRADE_CODE FOREIGN KEY(GRADE_CODE) 
                            REFERENCES USER_GRADE(GRADE_CODE);

-- SYS_C007114 -> PK_GRADE_CODE
-- 2. 제약조건 삭제
ALTER TABLE USER_GRADE
DROP CONSTRAINT SYS_C007114;

-- ex01) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 추가해주세요
-- ex02) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 삭제해주세요
-- ex03) USER_FOREIGN_KEY 테이블에 USER_DATE 컬럼의 자료형을 VARCHAR2(10)으로 바꿔주세요
-- ex04) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼의 이름을 REG_DATE로 
-- 변경해주세요
-- ex05) USER_FOREIGN_KEY 테이블의 이름을 USER_TBL로 바꿔주세요 (2가지)






